// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd544pWy7XUKb-1SXiOEZJWTRB8rPuUFI',
    appId: '1:229724811947:web:01425d8dbae3169d5efdee',
    messagingSenderId: '229724811947',
    projectId: 'diatrofi-8daa9',
    authDomain: 'diatrofi-8daa9.firebaseapp.com',
    storageBucket: 'diatrofi-8daa9.appspot.com',
    measurementId: 'G-JDXV41WSTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn-feI08SqyWwxTVkyRxLWs0diBCuQeiA',
    appId: '1:229724811947:android:d658e5d3c9323c3d5efdee',
    messagingSenderId: '229724811947',
    projectId: 'diatrofi-8daa9',
    storageBucket: 'diatrofi-8daa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO-FlZm3UG9u9bHYhJt8chHTm8tYa_kcI',
    appId: '1:229724811947:ios:fbbb2452e9ef758e5efdee',
    messagingSenderId: '229724811947',
    projectId: 'diatrofi-8daa9',
    storageBucket: 'diatrofi-8daa9.appspot.com',
    iosClientId: '229724811947-o0ceohsvdvojbh1jcg7smmgsvanhc5b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.diatfori',
  );
}
